```yaml
name: Windows Push
run-name: ${{ github.ref_name }} Windows push 🚀

on:
  push:
    branches:
      - master
      - main
      - "release/**"
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build-project:
    name: Build Windows 🪟
    uses: ./.github/workflows/build-project.yaml
    secrets: inherit
    permissions:
      contents: read

  create-release:
    name: Create Windows Release 🚀
    if: github.ref_type == 'tag'
    runs-on: ubuntu-24.04
    needs: build-project

    steps:
      - name: Check Release Tag
        id: check
        shell: bash
        run: |
          if [[ "${GITHUB_REF_NAME}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "validTag=true" >> "$GITHUB_OUTPUT"
            echo "version=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          else
            echo "validTag=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Download Windows Artifact
        if: steps.check.outputs.validTag == 'true'
        uses: actions/download-artifact@v4

      - name: Show Windows Files
        if: steps.check.outputs.validTag == 'true'
        shell: bash
        run: |
          echo "Windows files:"
          find . -type f \( -name "*.exe" -o -name "*.zip" \) -print

      - name: Create Windows Release
        if: steps.check.outputs.validTag == 'true'
        uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564
        with:
          draft: true
          prerelease: false
          tag_name: ${{ steps.check.outputs.version }}
          name: ${{ needs.build-project.outputs.pluginName }} ${{ steps.check.outputs.version }}
          files: |
            **/*.exe
            **/*.zip
```
